services:
  cadastro-postgres:
    image: postgres:15
    container_name: cadastro-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cadastrodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cadastro-network

  cadastro-api:
    image: kenshiro1337/cadastroapi:latest
    container_name: cadastro-api
    depends_on:
      - cadastro-postgres
    networks:
      - cadastro-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cadastro-postgres:5432/cadastrodb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8080:8080"
    command: ./gradlew bootRun

volumes:
  postgres_data:

networks:
  cadastro-network:
    driver: bridge
